### ISSUE TITLE
crash on image note

### ISSUE THREAD

**Issue by Shefaee** [BijoySingh/Material-Notes-Android-App#166]
`java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1360)`

**Comment by creativetrendsapps** [comment]
192MB image...
